#ifndef MULTIPLICATION_TYPES_H
#define MULTIPLICATION_TYPES_H
enum MultiplicationTypes {
    RANGED_TREE_THREADED,
    BLINDLY_THREADED_TREE,
    LATE_COMPARISON,
    TUPLE_ITERATION,
    OFFSET_TREE,
    GPU_MULTIPLICATION
};
#endif